repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: local
    hooks:
      - id: checkstyle
        name: Checkstyle (Java)
        language: system
        types: [java]
        entry: >
          bash -c '
          CHECKSTYLE_VERSION=10.12.4
          JAR=.checkstyle/checkstyle-${CHECKSTYLE_VERSION}-all.jar

          if [ ! -f "$JAR" ]; then
            mkdir -p .checkstyle
            curl -sSL -o "$JAR" \
              https://github.com/checkstyle/checkstyle/releases/download/checkstyle-${CHECKSTYLE_VERSION}/checkstyle-${CHECKSTYLE_VERSION}-all.jar
          fi

          java -jar "$JAR" -c checkstyle.xml "$@"
          ' --
